### ISSUE TITLE
Blank output on vercel site

### ISSUE THREAD

**Issue by surjithctly** [ThewApp/speedlify-actions-vercel#1]
Hello,

Thanks so much for this action, I just tried it and the action ran successfully and pushed a new build. However, after clicking on the category, the output is blank. 

See: https://w3c-speedlify.vercel.app/
Code: https://github.com/surjithctly/speedlify-vercel

What do you think the issue might be? 

Also, how can we make sure to run this action everyday?

**Comment by ThewBear** [comment]
I checked and looks like the results are showing now.

The actions will run everyday because we schedule them to run with [scheduled event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events)

https://github.com/ThewApp/speedlify-actions-vercel/blob/8d4e28b06f3ed7418ec74bf2162c0be8a7350ba2/.github/workflows/test-pages.yml#L6-L7

**Comment by surjithctly** [comment]
Yes, thank you. it works now.  May be cache. 

Regarding corn, why your demo site shows 1000+ hours 
![image](https://user-images.githubusercontent.com/1884712/115051750-03bc0680-9e92-11eb-8243-57ca4a7b2147.png)

If it runs daily, it should be less than 24 hours right?

Also daily cron shouldn't be `0 0 * * *`  ?

**Comment by surjithctly** [comment]
Also, the API urls contains old site data which is deleted from the code. It pushes, but doesn't delete old ones. 

https://w3c-speedlify.vercel.app/api/urls.json

**Comment by ThewBear** [comment]
I disabled this demo site https://speedlify-actions-vercel.vercel.app/ because it will consume my actions bandwidth. You can view my active instance here https://speedlify.thewdhanat.com/.

**Comment by ThewBear** [comment]
You have to delete [results branch](https://github.com/surjithctly/speedlify-vercel/commits/results) or that specific site folder in result branch to remove that old site otherwise it will still show up.

**Comment by surjithctly** [comment]
make sense. thank you.

**Comment by surjithctly** [comment]
I have changed the Test-pages cron to `- cron: "0 0 * * *"`  and Deploy Vercel to `- cron: "5 0 * * *"` to give time to finish the latest result. or it will run simultaneously and get old data. 

If you want I can do a PR for this.
