### ISSUE TITLE
update actions deploy to Vercel?

### ISSUE THREAD

**Issue by janwillemwilmsen** [ThewApp/speedlify-actions-vercel#2]
Hi Thew, 

After my 'Speedlify' site on Netlify broke (due to overusage) I searched for an alternative and found yours. 
Have installed the Vercel version. Running locally works fine, deploy to Github works fine, the build on Github works fine, but the deploy to Vercel fails. 

After looking at the demo site of the Speedlify-on-Vercel site I see that since February the updates stopped. Does this mean that the Deploy step is failing there as well? 

Have looked at 'deploy-vercel.yml' but I don't know what to change in order to fix the deploy step.
When searching for 'Github deploy to Vercel' I found this : https://github.com/marketplace/actions/vercel-action#github-actions (but still dont know which values I should use in the deploy-vercel.yml file to get it working again.

Hope you can take a look and know how to fix the deploy step. Going to try the Speedlify on GH pages next.

**Comment by ThewBear** [comment]
Hi 👋! I disabled the actions manually because it consumes my actions quota. You can see my current running instance and deploy to Vercel at https://github.com/ThewBear/speedlify.

Can you provide me your deploy to vercel repo? Did you provide the env secret?

> Add the following secrets to your repository:
> VERCEL_TOKEN: You vercel account token obtained from https://vercel.com/account/tokens
> VERCEL_PROJECT: Content of the .vercel/project.json file generated by vc link command.

**Comment by janwillemwilmsen** [comment]
Hi there!

Will take a look at your other repo.

- My repo is here:
https://github.com/janwillemwilmsen/bossche/ 

- Secrets are added also. Thought maybe I had to add 'orgID' and 'projID' from the .vercel/project.json to the secrets so added them as well. If you want to see : https://ibb.co/mbHykYY 

If you see anything wrong in my repo, please share!

**Comment by janwillemwilmsen** [comment]
After investigation of the GH Actions failed build, I found the error in build logs. 
See : https://ibb.co/Pt6PPKB
Not sure how to fix. But going to try now.

**Comment by ThewBear** [comment]
Could you confirm the content of `VERCEL_PROJECT` token? Is it a valid json string?

**Comment by janwillemwilmsen** [comment]
Hi Thew, 

I used the value of the 'projectId' as a secret, not the whole generated json-code in the project.json. 
After using the whole contents of the project.json file as the 'VERCEL_PROJECT' as a secret it is working! Nice! 

Thanks for your help!
